config/routes.rb
Rails.application.routes.draw do

  resources :uploads
  resources :abouts
  resources :members
  resources :events
  resources :contacts

  root 					'up_arise#Home'
  get 'signup'		=>	'users#new'
  put 'role'		=>  'users#update'
  get 'login'		=>	'sessions#new'
  post 'login'		=>	'sessions#create'
  delete 'logout'	=>	'sessions#destroy'
  
  resources :users 
  resources :articles

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_action :is_editor_or_admin, only: [:new, :edit, :create, :update, :destroy]

    def new
        @event = Event.new
    end
    
    def edit
        @event = Event.find(params[:id])
        if(@event.author != current_user.name)
        	redirect_to events_url
        end
    end
    
    def create
        @event = Event.new(event_params)
        @event.author = current_user.name;
        if @event.save
            redirect_to events_url
        else
            render 'new'
        end
    end
    
    def update
        @event = Event.find(params[:id])
        if @event.update(event_params)
            redirect_to events_url
        else 
            render 'edit'
        end
    end
        
    def show
        @event = Event.find(params[:id])
    end
    
    def index
        @events = Event.all
    end
    
    def destroy
        @event = Event.find(params[:id])
        if @event.author == current_user.name || current_user.user_role == "Admin"
        	@event.destroy
        end
        redirect_to events_url
    end
    
    private
        def event_params
            params.require(:event).permit(:title, :author, :text)
        end
        
        def is_editor_or_admin
        	redirect_to(events_url) unless (current_user.user_role == "Editor" || current_user.user_role == "Admin")
        end
    end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.cktext_area :text, rows: 10 %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Upcoming Events</h1>

<% if current_user != nil && (current_user.user_role == "Admin" || current_user.user_role == "Editor") %>
	<%= link_to 'New Event', new_event_path %>
<% end %>

<% @events.each do |event| %>
      <p>
  		<h3><%= event.title %></h3>
	  </p>
	  
	  <p>
  		Author: 
  		<%= event.author %>
	  </p>
 
	  <p>
		<%= raw event.text %>
	  </p>
      
     <% if current_user != nil && (current_user.user_role == "Admin" || current_user.user_role == "Editor") %>
	  	<%= link_to 'Edit event', edit_event_path(event) %> |
	  	<%= link_to 'Delete', event_path(event), method: :delete, data: {confirm: 'Are you sure you would like to delete this? ' } %>
	  	<%= link_to 'New event', new_event_path %>
      <% end %>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>