config/routes.rb
Rails.application.routes.draw do

  resources :uploads
  resources :abouts
  resources :members
  resources :events
  resources :contacts

  root 					'up_arise#Home'
  get 'signup'		=>	'users#new'
  put 'role'		=>  'users#update'
  get 'login'		=>	'sessions#new'
  post 'login'		=>	'sessions#create'
  delete 'logout'	=>	'sessions#destroy'
  
  resources :users 
  resources :articles

end

app/models/about.rb
class About < ActiveRecord::Base
	ActionView::Template.register_template_handler(:rb, :source.to_proc)
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController

	before_action :is_editor_or_admin, only: [:new, :edit, :create, :update, :destroy]

    def new
        @about = About.new
    end
    
    def edit
        @about = About.find(params[:id])
        if(@about.author != current_user.name)
        	redirect_to abouts_url
        end
    end
    
    def create
        @about = About.new(about_params)
        @about.author = current_user.name;
        if @about.save
            redirect_to abouts_url
        else
            render 'new'
        end
    end
    
    def update
        @about = About.find(params[:id])
        if @about.update(about_params)
            redirect_to abouts_url
        else 
            render 'edit'
        end
    end
        
    def show
        @about = About.find(params[:id])
    end
    
    def index
        @abouts = About.all
    end
    
    def destroy
        @about = About.find(params[:id])
        if @about.author == current_user.name || current_user.user_role == "Admin"
        	@about.destroy
        end
        redirect_to abouts_path
    end
    
    private
        def about_params
            params.require(:about).permit(:title, :author, :text)
        end
        
         def is_editor_or_admin
        	redirect_to(Members_url) unless (current_user.user_role == "Editor" || current_user.user_role == "Admin")
        end
    end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/views/abouts/_form.html.erb
<%= form_for(@about) do |f| %>
  <% if @about.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
      <% @about.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.cktext_area :text, rows: 10 %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/abouts/edit.html.erb
<h1>Editing About</h1>

<%= render 'form' %>

<%= link_to 'Back', abouts_path %>

app/views/abouts/index.html.erb
<h1>About</h1>

<% if @abouts.empty? && (current_user != nil && (current_user.user_role == "Admin" || current_user.user_role == "Editor") )%>
	<%= link_to 'Create Content', new_about_path %>
<% end %>

<% @abouts.each do |about| %>
      <p>
  		<h3><%= about.title %></h3>
	  </p>
 
	  <p>
		<%= raw about.text %>
	  </p>
      
      <% if current_user != nil && (current_user.user_role == "Admin" || current_user.user_role == "Editor") %>
      	<p>
  			Edited by:
  			<%= about.author %>
	  	</p>
	  	<%= link_to 'Edit Content', edit_about_path(about) %> |
	  	<%= link_to 'Delete', about_path(about), method: :delete, data: {confirm: 'Are you sure you would like to delete this? ' } %>
      <% end %>
<% end %>

app/views/abouts/new.html.erb
<h1>New About</h1>

<%= render 'form' %>

<%= link_to 'Back', abouts_path %>