config/routes.rb
Rails.application.routes.draw do

  resources :uploads
  resources :abouts
  resources :members
  resources :events
  resources :contacts

  root 					'up_arise#Home'
  get 'signup'		=>	'users#new'
  put 'role'		=>  'users#update'
  get 'login'		=>	'sessions#new'
  post 'login'		=>	'sessions#create'
  delete 'logout'	=>	'sessions#destroy'
  
  resources :users 
  resources :articles

end

app/models/about.rb
class About < ActiveRecord::Base
	ActionView::Template.register_template_handler(:rb, :source.to_proc)
end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true, length: {minimum: 1}
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
	mount_uploader :attachment, AttachmentUploader
end

app/models/user.rb
class User < ActiveRecord::Base
	
	attr_accessor :remember_token 
	mount_uploader :attachment, AttachmentUploader
	
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, 
		format: { with: VALID_EMAIL_REGEX },
		uniqueness: { case_sensitive: false }
	has_secure_password
	
	
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end
	
	def User.new_token
		SecureRandom.urlsafe_base64
	end
	
	def remember
    	self.remember_token = User.new_token
    	update_attribute(:remember_digest, User.digest(remember_token))
  	end
	
	def forget
		update_attribute(:remember_digest, nil)
	end
	
	def authenticated?(remember_token)
    	return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController

	before_action :is_editor_or_admin, only: [:new, :edit, :create, :update, :destroy]

    def new
        @about = About.new
    end
    
    def edit
        @about = About.find(params[:id])
        if(@about.author != current_user.name)
        	redirect_to abouts_url
        end
    end
    
    def create
        @about = About.new(about_params)
        @about.author = current_user.name;
        if @about.save
            redirect_to abouts_url
        else
            render 'new'
        end
    end
    
    def update
        @about = About.find(params[:id])
        if @about.update(about_params)
            redirect_to abouts_url
        else 
            render 'edit'
        end
    end
        
    def show
        @about = About.find(params[:id])
    end
    
    def index
        @abouts = About.all
    end
    
    def destroy
        @about = About.find(params[:id])
        if @about.author == current_user.name || current_user.user_role == "Admin"
        	@about.destroy
        end
        redirect_to abouts_path
    end
    
    private
        def about_params
            params.require(:about).permit(:title, :author, :text)
        end
        
         def is_editor_or_admin
        	redirect_to(Members_url) unless (current_user.user_role == "Editor" || current_user.user_role == "Admin")
        end
    end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :logged_in_user, only: [:edit, :update, :index, :destroy]
  before_action :admin_user,     only: [:destroy, :update, :edit]
  
  def index
  	@users = User.paginate(page: params[:page])
  end
  
  def show
  	@user = User.find(params[:id])
  end
  
  def destroy
  	User.find(params[:id]).destroy
    flash[:success] = "Account deleted"
    redirect_to users_url
  end
  
  def new
  	@user = User.new
  end
  
  def create
  	@user = User.new(user_params)
    if @user.save()
      log_in @user
      flash[:success] = "Welcome!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
  	@user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Account updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  private
  
  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation, :user_role, :user, :contact, :status, :description, :attachment)
  	end
  	
  	def logged_in_user
      unless logged_in?
      	store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    def admin_user
    	if (current_user.user_role == "Admin")
    	end
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def log_in(user)
		session[:user_id] = user.id
	end
	
	def remember(user)
		user.remember
    	cookies.permanent.signed[:user_id] = user.id
    	cookies.permanent[:remember_token] = user.remember_token
	end
	
	def current_user?(user)
		user == current_user
	end
	
	def current_user
		if (user_id = session[:user_id])
      		@current_user ||= User.find_by(id: user_id)
    	elsif (user_id = cookies.signed[:user_id])
      		user = User.find_by(id: user_id)
      		if user && user.authenticated?(cookies[:remember_token])
        		log_in user
        		@current_user = user
      		end
    	end
	end
	
	def logged_in?
		!current_user.nil?
	end
	
	def forget(user)
		user.forget
    	cookies.delete(:user_id)
    	cookies.delete(:remember_token)
	
	end
	
	def log_out
		forget(current_user)
		session.delete(:user_id)
   		@current_user = nil
	end
	
	def redirect_back_or(default)
    	redirect_to(session[:forwarding_url] || default)
    	session.delete(:forwarding_url)
 	end

	def store_location
    	session[:forwarding_url] = request.url if request.get?
  	end	
end

app/helpers/up_arise_helper.rb
module UpAriseHelper
	def full_title(page_title)
		base_title = "UP ARISE"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer id="contact" class="footer container">
	<div class="col-md-6">
	  <p>Contact Us</p>
	</div>
	<div class="col-md-6">  
	  <ul class="list-inline">
	    <li><a href="#"><span class="glyphicon glyphicon-globe sm-glyph" aria-hidden="true"></span></a></li>
	    <li><a href="#"><span class="glyphicon glyphicon-send sm-glyph" aria-hidden="true"></span></a></li>
	    <li><a href="#"><span class="glyphicon glyphicon-gift sm-glyph" aria-hidden="true"></span></a></li>
	  </ul>
	</div>         
</footer> 

app/views/layouts/_header.html.erb
<title>UP ARISE</title>
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "UP ARISE",	root_path, class:"a navbar-brand logo-hover", style:"color: #f4f4f4; font-weight: 900;" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse navbar-right">
          <ul class="nav navbar-nav">
            <li class="anchor"><%= link_to "Home", 	root_path %></li>
            <li><%= link_to "About",  root_path(anchor: "aboutus"), :class => "a anchor" %></li>
            <li><%= link_to "Executive Committee", 	root_path(anchor: "members"), :class => "a anchor" %></li>
            <li><%= link_to "Events", 	root_path(anchor: "events"), :class => "a anchor" %></li>
            <li><%= link_to "News", 	articles_path, :class => "a anchor"  %></li> 
            <li><%= link_to "Contact", 	root_path(anchor: "contact"), :class => "a anchor"  %></li>   
            <% if logged_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account<span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to "Profile", current_user %></li>
                    <li class="divider"></li>
                    <li class="dropdown-header">System</li>
                    <li><%= link_to "Settings", edit_user_path(current_user), :class => "a" %></li>
                    <li><%= link_to "Log out", logout_path, method: "delete", :class => "a" %></li>
                  </ul>

              </li>
              
            <% else %>
              <li><%= link_to "Log in", login_path, :class => "a anchor" %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/_header2.html.erb
<div class="col-sm-10 col-sm-offset-2 col-md-11 col-md-offset-1 main cover-all">   
      <% if current_page?(user_path(current_user)) %>
        <div class="container-fluid center-block intro-header"> 
       <% else %>
       <div class="container-fluid center-block"> 
       <% end %>
            <div class="container-fluid center-block intro-header">       
             <nav class="col-sm-12 col-md-12 navbar navbar-inverse navbar-fixed-top navbar-custom">
                  <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Dashboard</a>
                  </div>
                  <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                      <li><a href="#">Profile</a></li>
                      <li><a href="#">Members</a></li>
                      <li><a href="#">Search</a></li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Create Article..</a></li>
                          <li><%= link_to "Visit Website..", root_path, :class => "a" %></li>
                          <li class="divider"></li>
                          <li class="dropdown-header">System</li>
                          <li><%= link_to "Settings", edit_user_path(current_user), :class => "a" %></li>
                          <li><%= link_to "Log out", logout_path, method: "delete", :class => "a" %></li>
                        </ul>
                      </li>
                  </div>
              </nav>

app/views/layouts/_shim.html.erb
<!==[if 1t IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<title>Dashboard | UP ARISE</title>
<div class="container-fluid center-block bg-white cover-all">
        <div class="row center-block">
          <div class="col-sm-2 col-md-1 sidebar text-center">
            <ul class="nav nav-sidebar">
              <li><a><%= image_tag("arise-logo.png", class: "img img-responsive img-logo") %></a></li>
            </ul>
            <ul class="nav nav-sidebar">
              <li class="active"><a href="#">Navigation<span class="sr-only">(current)</span></a></li>
            </ul>
            <ul class="nav nav-sidebar">
              <li><%= link_to "", user_path(current_user), :class => "a glyphicon glyphicon-home" %></li>
            </ul>
            <ul class="nav nav-sidebar">
              <li>
               <%= link_to users_path do %>
                  <span class="a glyphicon glyphicon-user"></span>
                <% end %>
             </li>
            </ul>
            <ul class="nav nav-sidebar">
              <li>
               <%= link_to articles_path do %>
                  <span class="a glyphicon glyphicon-edit"></span>
                <% end %>
             </li>
            </ul>
            <ul class="nav nav-sidebar">
              <li>
               <%= link_to edit_user_path(current_user) do %>
                  <span class="a glyphicon glyphicon-wrench"></span>
                <% end %>
             </li>
            </ul>
            <ul class="nav nav-sidebar">              
             <li>
               <%= link_to logout_path, method: "delete" do %>
                  <span class="a glyphicon glyphicon-off"></span>
                <% end %>
             </li>
            </ul>
          </div>
          
         <div class="col-sm-10 col-sm-offset-2 col-md-11 col-md-offset-1 main cover-all bg-white">
            <% if current_page?(user_path(current_user)) %>
                <div class="container-fluid center-block intro-header coverpage"> 
            <% else %>
                <div class="container-fluid center-block intro-header"> 
            <% end %>
             <nav class="col-sm-12 col-md-12 navbar navbar-inverse navbar-fixed-top navbar-custom">
                  <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Dashboard</a>
                  </div>
                  <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                      <li><%= link_to "Profile", user_path(current_user), :class => "a" %></li>
                      <li><%= link_to "Members", users_path, :class => "a" %></li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><%= link_to "Articles", articles_path, :class => "a" %></li>
                          <li><%= link_to "Visit Website..", root_path, :class => "a" %></li>
                          <li><%= link_to "Settings", edit_user_path(current_user), :class => "a" %></li>
                           <li class="divider"></li>
                          <li><%= link_to "Log out", logout_path, method: "delete", :class => "a" %></li>
                        </ul>
                      </li>
                  </div>
              </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
     <% if current_page?(root_path) || current_page?(login_path) || current_page?(signup_path) || current_page?(articles_path) || current_page?(new_article_path)  %>
       <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
     <%  elsif @article != nil && (current_page?(article_path(@article)) || current_page?(edit_article_path(@article))) %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
     <%  elsif !logged_in? && current_page?(login_path) %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
     <% else %>
       <%= stylesheet_link_tag    'dashboard', media: 'all', 'data-turbolinks-track' => true %>
     <% end %>
   
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <link href='http://fonts.googleapis.com/css?family=Pacifico|Cookie|Damion|Sacramento|Open+Sans' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Parisienne|Allura|Dancing+Script|Leckerli+One' rel='stylesheet' type='text/css'>
  </head>

  <body role="document">
    <% if current_page?(root_path) || current_page?(login_path) || current_page?(signup_path) || current_page?(articles_path) || current_page?(new_article_path) %>
      <%= render 'layouts/header' %>
    <%  elsif @article != nil && (current_page?(article_path(@article)) || current_page?(edit_article_path(@article))) %>
       <%= render 'layouts/header' %>
    <% else %>
      <%= render 'layouts/sidebar' %>
    <% end %>
      <%= yield %>
     <% if current_page?(root_path) || current_page?(login_path) || current_page?(signup_path) || current_page?(articles_path) || current_page?(new_article_path)  %>
      <%= render 'layouts/footer' %>
    <%  elsif @article != nil && (current_page?(article_path(@article)) || current_page?(edit_article_path(@article))) %>
      <%= render 'layouts/footer' %>
    <% end %>
  </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id = "error_explanation">
		<div class = "alert alert-danger">
			The form contains <%= pluralize(@user.errors.count, "error") %>
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>