config/routes.rb
Rails.application.routes.draw do

  resources :uploads
  resources :abouts
  resources :members
  resources :events
  resources :contacts

  root 					'up_arise#Home'
  get 'signup'		=>	'users#new'
  put 'role'		=>  'users#update'
  get 'login'		=>	'sessions#new'
  post 'login'		=>	'sessions#create'
  delete 'logout'	=>	'sessions#destroy'
  
  resources :users 
  resources :articles

end

app/models/member.rb
class Member < ActiveRecord::Base
	mount_uploader :attachment, AttachmentUploader
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

	before_action :is_editor_or_admin, only: [:new, :edit, :create, :update, :destroy]

    def new
        @member = Member.new
    end
    
    def edit
        @member = Member.find(params[:id])
        if(@member.author != current_user.name)
        	redirect_to members_url
        end
    end
    
    def create
        @member = Member.new(member_params)
        @member.author = current_user.name;
        if @member.save
            redirect_to members_url
        else
            render 'new'
        end
    end
    
    def update
        @member = Member.find(params[:id])
        if @member.update(member_params)
            redirect_to members_url
        else 
            render 'edit'
        end
    end
        
    def show
        @member = Member.find(params[:id])
    end
    
    def index
        @members = Member.all
    end
    
    def destroy
        @member = Member.find(params[:id])
        if @member.author == current_user.name || current_user.user_role == "Admin"
        	@member.destroy
        end
        redirect_to members_url
    end
    
    private
        def member_params
            params.require(:member).permit(:title, :author, :text)
        end
        
        def is_editor_or_admin
        	redirect_to(members_url) unless (current_user.user_role == "Editor" || current_user.user_role == "Admin")
        end
    end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.cktext_area :text, rows: 10 %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Members</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Executive Committee</h1>

<% if current_user != nil && (current_user.user_role == "Admin" || current_user.user_role == "Editor") %>
	<%= link_to 'New Member', new_member_path %>
<% end %>

<% @members.each do |member| %>
      <p>
  		<h3><%= member.title %></h3>
	  </p>
 
	  <p>
		<%= raw member.text %>
	  </p>
      
      <% if current_user != nil && (current_user.user_role == "Admin" || current_user.user_role == "Editor") %>
      	<p>
  			Edited by:
  			<%= member.author %>
	  	</p>
	  	<%= link_to 'Edit Member', edit_member_path(member) %> |
	  	<%= link_to 'Delete', member_path(member), method: :delete, data: {confirm: 'Are you sure you would like to delete this? ' } %>
      <% end %>
<% end %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>